### PR TITLE
chore: upgrade node images to last LTS releases

### PR DESCRIPTION
**Pull request by clemstoquart**

### CODE REVIEW

**Comment by Crow-EH** [comment]
LGTM :+1: 

However, we need to find out why aws is failing

**Comment by Mallear** [comment]
> However, we need to find out why aws is failing

Seems GCC has trouble. Maybe we should base python related container on debian images. Musl is a pain, most of the time we need to re-install a big part of libc before running our scripts because of CPython packages.

**Comment by Crow-EH** [comment]
Off, I just read this a minute ago: https://pythonspeed.com/articles/alpine-docker-python/

I'm OK with you @Mallear. WDYT @mremi ?

**Comment by Mallear** [comment]
I will open an issue tomorrow to discuss about it and start refactoring python images for upgrade and cleaning python based images.

**Comment by saugereau** [comment]
> I will open an issue tomorrow to discuss about it and start refactoring python images for upgrade and cleaning python based images.

Does this mean that we're waiting for your branch @Mallear before merging this one ?

**Comment by Mallear** [comment]
> > I will open an issue tomorrow to discuss about it and start refactoring python images for upgrade and cleaning python based images.
> 
> Does this mean that we're waiting for your branch @Mallear before merging this one ?

Not at all, you can merge this PR and I'll rebase my branch :)

**Comment by Crow-EH** [comment]
> > > I will open an issue tomorrow to discuss about it and start refactoring python images for upgrade and cleaning python based images.
> > 
> > 
> > Does this mean that we're waiting for your branch @Mallear before merging this one ?
> 
> Not at all, you can merge this PR and I'll rebase my branch :)

Well, we have to wait anyway because it fixes the CI

**Comment by Mallear** [comment]
> > > > I will open an issue tomorrow to discuss about it and start refactoring python images for upgrade and cleaning python based images.
> > > 
> > > 
> > > Does this mean that we're waiting for your branch @Mallear before merging this one ?
> > 
> > 
> > Not at all, you can merge this PR and I'll rebase my branch :)
> 
> Well, we have to wait anyway because it fixes the CI

As the PR only modify node image and failing image is AWS, maybe you could merge without green CI ?

**Comment by Crow-EH** [comment]
> > > > > I will open an issue tomorrow to discuss about it and start refactoring python images for upgrade and cleaning python based images.
> > > > 
> > > > 
> > > > Does this mean that we're waiting for your branch @Mallear before merging this one ?
> > > 
> > > 
> > > Not at all, you can merge this PR and I'll rebase my branch :)
> > 
> > 
> > Well, we have to wait anyway because it fixes the CI
> 
> As the PR only modify node image and failing image is AWS, maybe you could merge without green CI ?

I don't think I can bypass this check, since I'm not an owner.

**Comment by saugereau** [comment]
I can merge if needed, but we can propably merge @Mallear refactoring PR today (so I hape to, because i would like to add new docker image with ibm cli )

**Comment by saugereau** [comment]
@Mallear PR was merged, @clemstoquart can you rebase please ?

**Comment by clemstoquart** [comment]
@saugereau rebase done

**Pull request merged**
