### PR TITLE
Change image naming policy to create a repo per image

### PR DESCRIPTION
**Pull request by Mallear**
Here is my code linked to #182 . Format of image renaming is open to discussion.

### CODE REVIEW

**Comment by Mallear** [comment]
That's why I choose to add `-ci` at the end of the name. But still debatable 😄

**Comment by Crow-EH** [comment]
Then why not `gitlab-ci` ? We could make images for other ci systems in the future.

**Comment by Mallear** [comment]
@Crow-EH If we change our CI system, won't we still use docker images ? I don't think images need to change between gitlab, travis or any CI system based on docker images

**Comment by Crow-EH** [comment]
I mean we could offer multiple target systems one day.
Anyway today the readme clearly says `The targeted usage of those images is GitlabCI` so I think our tags should be explicit too.

**Comment by mremi** [comment]
"GitLab" is mentioned in README but the images can be used everywhere, no matter the solution (for local development as well).
I'd use `ekino/dev-{image}:{version}` or still `buildbox` but maybe less explicit?

**Comment by Crow-EH** [comment]
In that case, I'm in favor of `buildbox` too.

**Comment by Mallear** [comment]
Changed to ci-image according to @rande comment in #182

**Comment by rande** [comment]
> I mean we could offer multiple target systems one day.
> Anyway today the readme clearly says `The targeted usage of those images is GitlabCI` so I think our tags should be explicit too.

We can also change the tagline ;) The project has evolved a lot.

**Comment by Mallear** [comment]
I've rebased master on this branch to fix conflicting code. I took the time to make better string building for image name.

Is everyone OK with `ekino/ci-image` pattern or should we discuss more/make a poll to choose image naming convention ?

**Comment by mremi** [comment]
👎 for `ci`, because can be used locally too

**Comment by flou** [comment]
I believe these images are mostly meant for running tests and deployment in a CI environment, but of course they can be used for other uses, any image can be used locally.

In my experience the Python, DinD, Serverless, Terraform images (most of them actually) don't provide much value for local development.
So maybe some images should be prefixed with `dev` but I think `ci` is a better prefix than `dev` or `buildbox`.

**Comment by GuillaumeAmat** [comment]
IMHO, `dev` is too generic, `ci` excludes local usage and `buildbox` is about building things only.

I know that I add some noise to the discussion but, if I need to answer the question, I would pick something like `dev-container-FLAVOR` or `devbox-FLAVOR`.

**Comment by Mallear** [comment]
I have rebased master on this branch.

According to the Slack poll, we will go with `ci-image` pattern.

**Comment by Mallear** [comment]
I'm back. I've rebased new changes from master.

I don't think there is anything more to do for this PR and we are good to go with this change.
I'm available to follow the next release for troubleshooting if needed.

@mremi @rande @Crow-EH @axelpavageau

**Pull request merged**
