### PR TITLE
feat(tezos): add tezos image for qa

### PR DESCRIPTION
**Pull request by catsoap**
Hello I propose to add this image for Tezos blockchain

did not add config test because the added programs do not have option to display version, but tested locally, everything ok

### CODE REVIEW

**Comment by Bladrak** [comment]
@catsoap so far so good, what's pending for WIP status?

**Comment by catsoap** [comment]
Hello ! it needs an update because SmartPy url has changed, and maybe we can add truffle@tezos and ligo, I'll do an update later today !

**Comment by catsoap** [comment]
@Bladrak It's ok now

**Comment by Bladrak** [comment]
@catsoap the truffle config thing might be worth documenting within a readme file next to the dockerfile, would you mind adding that?

**Comment by catsoap** [comment]
yep, but I'm sorry, I was wrong, it's not currently possible https://github.com/trufflesuite/truffle/blob/alphaTez/packages/compile-ligo/index.js#L88, will have a look at what we can do

**Comment by catsoap** [comment]
Hi sir, I removed truffle, the image is currently good enough, we can:
- compile smartpy
- compile ligo
- test with pytezos

**Comment by Bladrak** [comment]
Ok, looks good to me, thanks!

**Pull request merged**
