### PR TITLE
chore(ci): lint matrix and new include override

### PR DESCRIPTION
**Pull request by Crow-EH**
According to a Github dev (https://github.com/actions/runner/issues/343#issuecomment-590634907), we can now directly use `include` to create new matrix entries like we did on Travis :tada:.

I also removed useless intermediate env variables and linted the matrix a bit to change the case and have a clean "column" look.

While we're at it : Do you prefer the "column style" or the "list style", or the previous style?

Column style (really easy to read, but awful to maintain):
```
strategy:
  matrix:
    include:
      - { image: ansible, version: 2.9  }
      - { image: aws    , version: 1    }
      - { image: aws    , version: 2    }
      - { image: aws    , version: 3    }
      - { image: chrome , version: 1    }
      - { image: dind   , version: 1    }
      - { image: golang , version: 1.14 }
```

List style (not really easy to read, but easy to maintain):
```
strategy:
  matrix:
    include:
      - image: ansible
        version: 2.9
      - image: aws
        version: 1
      - image: aws
        version: 2
      - image: aws
        version: 3
      - image: chrome
        version: 1
      - image: dind
        version: 1
      - image: golang
        version: 1.14
```

Previous style (easily see which image has multiple versions, easy to maintain):
```
strategy:
  matrix:
    include:
      - { image: ansible, version: 2.9 }
      - { image: aws, version: 1 }
      - { image: aws, version: 2 }
      - { image: aws, version: 3 }
      - { image: chrome, version: 1 }
      - { image: dind, version: 1 }
      - { image: golang, version: 1.14 }
```

**Let's vote** with :heart: for column style, with :rocket: for list style and with :tada: for the previous style !

### CODE REVIEW

**Comment by Mallear** [comment]
List style for me.
Managing a "graphic" columns using spaces will be awefull.

**Comment by Crow-EH** [comment]
> List style for me.
> Managing a "graphic" columns using spaces will be awefull.

True.

There's also the option to keep it inlined as it is today :
```
strategy:
  matrix:
    include:
      - { image: ansible, version: 2.9 }
      - { image: aws, version: 1 }
      - { image: awslnx-systemd, version: 2 }
      - { image: azure, version: 2 }
      - { image: chrome, version: 1 }
      - { image: dind, version: 1 }
      - { image: golang, version: 1.14 }
```

I'll add the option in the vote.

**Comment by Crow-EH** [comment]
I fell back to the previous style since there aren't that much votes. We can change the style later.

Ready to merge if you're okay with it @Mallear

**Comment by Mallear** [comment]
> 
> 
> I fell back to the previous style since there aren't that much votes. We can change the style later.
> 
> Ready to merge if you're okay with it @Mallear

It's good for me ! Go one and merge :D

**Pull request merged**
