### PR TITLE
Core: Script fixes for testing local script & disable push during PR CI pipelines

### PR DESCRIPTION
**Pull request by Mallear**
Change test configuration struct to allow mounting volume for local test scripts.

- `cmd_test` replaced by a dict
```
test_config:
    volume: dir:/path/to/mount  # If needed - absolute local path is build inside the script
    cmd: [...]   # List of test commands
```

- Print error output if last test fails
- Print command stdout in debug mode
- Had to remove the `auto_remove` option to get the command logs, the script now prune all non-running container at the end of all tests even if one fails

-------

Disable push during PR CI pipelines

- Fix TRAVIS_TAG value check
- Fix merging PR to master case test

Note: Sorry for space trimming 😄

### CODE REVIEW

**Comment by mremi** [comment]
To make sure it works as expected, can you make a PHP test fail (by adding a non-existent PHP extension for instance) ?

Another issue, seems that Travis login and push to the registry against a PR, and so alter the images before the team validates it.

**Comment by Mallear** [comment]
> To make sure it works as expected, can you make a PHP test fail (by adding a non-existent PHP extension for instance) ?
> 
> Another issue, seems that Travis login and push to the registry against a PR, and so alter the images before the team validates it.

Build 1894 is a failing build triggered by adding ssh2 extension check for php 7.3.

I will take a look on the push issue.

**Comment by mremi** [comment]
Build [#1894](https://travis-ci.org/ekino/docker-buildbox/builds/583022832) failed as expected 👌

**Comment by Mallear** [comment]
@mremi 
I have fixed to docker push issue and updated PR title and description consequently.

**Comment by mremi** [comment]
Thanks @Mallear !

**Pull request merged**
