### PR TITLE
feat(java): upgrade java to 8u181 and 10.0.2, and lock 11 to 11.0.1

### PR DESCRIPTION
**Pull request by Crow-EH**

### CODE REVIEW

**Comment by mremi** [comment]
Could you please update `CHANGELOG.md`?

**Comment by Crow-EH** [comment]
Ah yes my bad, I forgot.

**Comment by Crow-EH** [comment]
Done

**Comment by fpavageau** [comment]
LGTM 👍

**Comment by Crow-EH** [comment]
Thank you @fpavageau . Merged since all checks passed.

**Pull request merged**
